version: "3"

services:
  webapp:
    container_name: contenedor_app
    restart: always
    build: .
    ports:
      - "6000:3000"
    links: 
      - database
  database:
    container_name: contenedor_db_petlandia
    image: mongo
    ports:
      - "27019:27017"